"""HOD-ready email composer.

Builds a multipart MIME message with the vendor clarification matrix
rendered inline (HTML + plain text fallback) and the TBE workbook + the
clarification .docx attached. Writes both a ``.eml`` (raw RFC 2822) and
a ``.html`` (for preview in a browser) to ``deliverables/``.

**Never sends** -- composing only. Sending is the procurement team's
responsibility.
"""

from __future__ import annotations

import argparse
import json
import logging
from datetime import datetime
from email import policy
from email.message import EmailMessage
from html import escape
from pathlib import Path

from .packages import NOT_DECLARED, by_key
from .scoring import make_ref


log = logging.getLogger("gen_email")

DELIVERABLES_ROOT = Path("deliverables")
EVIDENCE_ROOT = Path("evidence")


CLARIFICATION_ROWS = (
    ("Compliance tally (FC/PC/DNC)",   "compliance_tally"),
    ("Thermal design",                 "thermal_design"),
    ("Reliability",                    "reliability"),
    ("BoM origin",                     "bom_origin"),
    ("Service network",                "service_network"),
    ("Connectivity",                   "connectivity"),
    ("OEM / installed base",           "installed_base"),
    ("CTQ deviations",                 "ctq_deviations"),
)


def _render_compact(field: dict | None) -> str:
    if not field:
        return NOT_DECLARED
    value = field.get("value", {})
    if not isinstance(value, dict):
        return str(value)
    parts = []
    for k, v in value.items():
        if k in ("source_file", "sheet", "row", "row_range", "verbatim_quote"):
            continue
        if isinstance(v, (dict, list)):
            v = json.dumps(v, default=str)[:80]
        parts.append(f"{k}={v}")
        if len(parts) >= 3:
            break
    return "; ".join(parts) if parts else NOT_DECLARED


def _build_html(package, vendors_evidence: dict[str, dict]) -> str:
    rows_html = []
    for vendor, evidence in vendors_evidence.items():
        rows_html.append(f"<h3>{escape(vendor)}</h3>")
        rows_html.append("<table border='1' cellpadding='4' cellspacing='0' "
                         "style='border-collapse:collapse;font-family:Arial,sans-serif;font-size:11px;'>")
        rows_html.append("<tr style='background:#eee;font-weight:bold;'>"
                         "<th>Criterion</th><th>Declaration</th><th>Ref</th></tr>")
        for label, ev_key in CLARIFICATION_ROWS:
            field = evidence.get(ev_key)
            decl = escape(_render_compact(field))
            ref = escape(make_ref(field))
            highlight = " style='background:#fdd;'" if NOT_DECLARED in decl else ""
            rows_html.append(
                f"<tr{highlight}><td>{escape(label)}</td>"
                f"<td>{decl}</td><td><code>{ref}</code></td></tr>"
            )
        rows_html.append("</table>")

    return f"""<!doctype html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;font-size:12px;color:#222;">
<p>Hi HOD,</p>
<p>Attached is the deterministic Technical Bid Evaluation for
<strong>{escape(package.display_name)}</strong> ({escape(package.key)}).
Weights applied: Design Concept = {package.weights.design_concept},
Ease of Operation = {package.weights.ease_of_operation}. Capex rows are
left blank for Procurement Team assessment.</p>

<p>Vendor clarification matrix inline below; the full TBE
(<code>TBE-{escape(package.key)}-*.xlsx</code>) and clarification matrix
(<code>{escape(package.key)}-vendor-clarification.docx</code>) are attached.</p>

{''.join(rows_html)}

<p>All cells highlighted red are <strong>{NOT_DECLARED}</strong> in the
vendor offer and have the prescribed penalty applied per the locked
scoring rules.</p>

<p>Generated by the Krayavikrayam RAG-TBE pipeline on
{datetime.utcnow().isoformat(timespec='seconds')} UTC.</p>
</body></html>
"""


def _build_text(package, vendors_evidence: dict[str, dict]) -> str:
    lines = [
        "Hi HOD,",
        "",
        f"Attached is the deterministic Technical Bid Evaluation for "
        f"{package.display_name} ({package.key}).",
        f"Weights: Design Concept = {package.weights.design_concept}, "
        f"Ease of Operation = {package.weights.ease_of_operation}.",
        "Capex rows are left blank for Procurement Team assessment.",
        "",
        "Vendor clarification matrix:",
        "",
    ]
    for vendor, evidence in vendors_evidence.items():
        lines.append(f"--- {vendor} ---")
        for label, ev_key in CLARIFICATION_ROWS:
            field = evidence.get(ev_key)
            decl = _render_compact(field)
            lines.append(f"  {label}: {decl}  [{make_ref(field)}]")
        lines.append("")
    lines.append(f"Generated {datetime.utcnow().isoformat(timespec='seconds')} UTC.")
    return "\n".join(lines)


def compose_email(
    package_key: str,
    vendors: list[str],
    to: str = "hod-procurement@example.invalid",
    cc: list[str] | None = None,
    attachments: list[Path] | None = None,
    evidence_root: Path = EVIDENCE_ROOT,
    out_root: Path = DELIVERABLES_ROOT,
) -> tuple[Path, Path]:
    package = by_key(package_key)
    vendors_evidence: dict[str, dict] = {}
    for vendor in vendors:
        p = evidence_root / package.key / f"{_safe(vendor)}.json"
        vendors_evidence[vendor] = json.loads(p.read_text()) if p.exists() else {}

    html_body = _build_html(package, vendors_evidence)
    text_body = _build_text(package, vendors_evidence)

    msg = EmailMessage(policy=policy.SMTP)
    msg["Subject"] = f"[TBE] {package.display_name} -- HOD review pack"
    msg["From"] = "krayavikrayam-pipeline@example.invalid"
    msg["To"] = to
    if cc:
        msg["Cc"] = ", ".join(cc)
    msg["Date"] = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")
    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")

    for att in attachments or []:
        p = Path(att)
        if not p.exists():
            log.warning("Attachment missing, skipping: %s", p)
            continue
        maintype, subtype = _guess_ctype(p)
        msg.add_attachment(p.read_bytes(), maintype=maintype, subtype=subtype, filename=p.name)

    out_root.mkdir(parents=True, exist_ok=True)
    eml_path = out_root / f"{package.key}-hod-email.eml"
    html_path = out_root / f"{package.key}-hod-email.html"
    eml_path.write_bytes(bytes(msg))
    html_path.write_text(html_body)
    log.info("Wrote email: %s + %s", eml_path, html_path)
    return eml_path, html_path


def _guess_ctype(path: Path) -> tuple[str, str]:
    suffix = path.suffix.lower()
    if suffix == ".xlsx":
        return ("application", "vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    if suffix == ".xlsm":
        return ("application", "vnd.ms-excel.sheet.macroEnabled.12")
    if suffix == ".docx":
        return ("application", "vnd.openxmlformats-officedocument.wordprocessingml.document")
    if suffix == ".pdf":
        return ("application", "pdf")
    return ("application", "octet-stream")


def _safe(name: str) -> str:
    return "".join(c if c.isalnum() or c in "-_." else "_" for c in name)


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    parser = argparse.ArgumentParser(description="Compose HOD email (does not send).")
    parser.add_argument("--package", required=True)
    parser.add_argument("--vendors", required=True)
    parser.add_argument("--to", default="hod-procurement@example.invalid")
    parser.add_argument("--cc", default="")
    parser.add_argument("--attach", action="append", default=[], help="Path(s) to attach")
    parser.add_argument("--evidence-root", default=str(EVIDENCE_ROOT))
    parser.add_argument("--out-root", default=str(DELIVERABLES_ROOT))
    args = parser.parse_args(argv)
    vendors = [v.strip() for v in args.vendors.split(",") if v.strip()]
    cc = [c.strip() for c in args.cc.split(",") if c.strip()]
    eml, html = compose_email(
        package_key=args.package,
        vendors=vendors,
        to=args.to,
        cc=cc,
        attachments=[Path(a) for a in args.attach],
        evidence_root=Path(args.evidence_root),
        out_root=Path(args.out_root),
    )
    print(eml)
    print(html)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
